name: Run Backend Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          cd back-end || exit 1 
          npm install

      - name: Run Tests
        run: |
          cd back-end || exit 1 
          npm test
