name: Run Backend Tests

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: back-end/package-lock.json

      - name: Install dependencies
        working-directory: ./back-end
        run: npm ci

      - name: Build
        working-directory: ./back-end
        run: npm run build --if-present

      - name: Test
        working-directory: ./back-end
        run: npm test
