name: Run Backend Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd back-end  # Adjust if your backend code is in a folder called "back-end"
          npm ci

      - name: Run tests
        run: |
          cd back-end  # Adjust if your backend code is in a folder called "back-end"
          npm test
