name: Run Backend Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd back-end || exit 1  # Exit if the directory doesn't exist
          npm install || exit 1  # Exit if npm install fails
          working-directory: back-end

      - name: Run tests
        run: |
          cd back-end || exit 1  # Exit if the directory doesn't exist
          npm test server.test.js || exit 1  # Exit if npm test fails
          working-directory: back-end
